---
- name: test playbook
  include: healthcheck.yml

- name: reload redis acl
  command: "{{ redis_command }} acl load"
  when: '"redis_start_service" == "true"'

- name: restart redis
  ansible.builtin.service:
    name: redis
    state: "restarted"


- name: restart sentinel
  ansible.builtin.service:
    name: sentinel
    state: "restarted"


- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

