---
scenario:
  name: cluster
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    #- idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: redis-master
    image: artifactory.arionbanki.is/docker-local/ansible-molecule/ubuntu:20.04 
    pre_build_image: true
    privileged: true
    network: newnet
    published_ports:
      - 6379/tcp
      - 26379/tcp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - redis_master
    tmpfs:
      - /run
      - /tmp
  - name: redis-slave-1
    image: artifactory.arionbanki.is/docker-local/ansible-molecule/ubuntu:20.04 
    pre_build_image: true
    privileged: true
    network: newnet
    published_ports:
      - 6379/tcp
      - 26379/tcp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - redis_slave  
    tmpfs:
      - /run
      - /tmp
  - name: redis-slave-2
    image: artifactory.arionbanki.is/docker-local/ansible-molecule/ubuntu:20.04 
    pre_build_image: true
    network: newnet
    published_ports:
      - 6379/tcp
      - 26379/tcp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /tmp
    groups:
      - redis_slave 
    privileged: true
provisioner:
  name: ansible
  log: true
  inventory:
    host_vars:
      redis_masterip: 192.5.0.2
      redis-master:
        redis_is_master: true
        redis_masterip: 192.5.0.2
      redis-slave-1:
        redis_is_master: false
        redis_masterip: 192.5.0.2
      redis-slave-2:
        redis_is_master: false
        redis_masterip: 192.5.0.2
verifier:
  name: testinfra
  #directory: ../../tests/*
lint: |
  ansible-lint .

