---
# Those values are for testing on local
redis_default_user: default
redis_default_password: admin
# Require authentication to Redis with a password.
redis_replica_user: "replicauser"
redis_replica_password: "replicapass"

redis_sentinel_admin: "sentinel"
redis_sentinel_password: "sentineladmin"
# some examples:
# service access to 1 namespace: acl setuser test on >test +set +get ~namespace:*
redis_users:
  - default: 
    name: "{{ redis_default_user }}"
    password: "{{ redis_default_password }}"
    command: ~* &* +@all
  - admin: 
    name: admin
    #password: adminpass 
    password: "#713bfda78870bf9d1b261f565286f85e97ee614efe5f0faf7c34e7ca4f65baca"
    command: +@admin
  - replicauser:
    name: "{{ redis_replica_user }}"
    password: "{{ redis_replica_password }}"
    command: ~* &* +@all
  - appuser1:
    name: redisservice 
    #password: redisservicepassword
    password:  "#b6914d00d5caa6ad26841608cacf27dd73ee34bfc7394e3750c72d23a8f51340" 
    command: allcommands -@dangerous +acl|whoami allkeys  
# Dont add password or disabled it, auto failover wont work
sentinel_users:
 # - default: 
 #   name: "{{ redis_default_user }}"
 #   password: "{{ redis_default_password }}"
 #   command: ~* &* +@all
  - admin: 
    name: admin
    password: adminpass 
    command: ~* &* +@all
  - replicauser:
    name: "{{ redis_replica_user }}"
    password: "{{ redis_replica_password }}"
    command: ~* &* +@all
