---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance
    image: artifactory.arionbanki.is/docker-local/ansible-molecule/ubuntu:20.04 
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  options:
    vvv: True
verifier:
  name: ansible
#lint: |
#  set -e
#  yamllint .
#  ansible-lint .
