---
- name: fs.file Description COnfig
  ansible.posix.sysctl:
    name: fs.file-max
    value: "65536"
    state: present
    reload: yes
  changed_when: false
  tags: notest

- name: enable overcommit in sysctl
  sysctl:
    name: vm.overcommit_memory
    value: "1"
    state: present
    reload: yes
    ignoreerrors: yes
  tags: notest


- name: Increase TCP Backlog requires for Redis
  sysctl:
    name: net.core.somaxconn
    value: "65535"
    state: present
    reload: yes
    ignoreerrors: yes
  tags: notest


- name: Disabled HugePages
  command: "echo 'never' > /sys/kernel/mm/transparent_hugepage/enabled"
  changed_when: false
  
- name: "UFW - Redis Replication"
  ufw:
    rule: allow
    port: "{{ port_item }}"
  loop:
    - 6379
    - 26379 
  loop_control:
        loop_var: port_item
  tags: notest


- name: check if redis user exists (ignore errors)
  command: id redis
  ignore_errors: yes
  changed_when: false
  register: user_exists

- name: add redis group
  group:
    name: redis
    state: present
  when: user_exists is failed

- name: add redis user
  user:
    name: redis
    group: redis
    comment: "Redis"
    home: /home/redis
    shell: /bin/false
    system: yes
  when: user_exists is failed
# Directorioes Needed
- name: Ensure Redis configuration dir exists.
  file:
    path: /etc/redis"
    state: directory
    mode: 0755

- name: create run/redis
  file:
    path: /run/redis
    state: directory
    owner: redis
    mode: 0770

- name: create run/sentinel
  file:
    path: /run/sentinel
    state: directory
    owner: redis
    mode: 0770

- name: Ensure /var/lib/redis
  file:
    path: /var/lib/redis
    state: directory
    owner: redis
    mode: 0770
 
- name: Ensure Redis Permissions files redis
  file: 
    path: /etc/redis  
    owner: redis 
    group: redis 
    mode: 0770
    recurse: yes
 
- name: Ensure Redis Permissions files logs
  file: 
    path: /var/log/redis  
    owner: redis 
    group: redis 
    mode: 0770
    recurse: yes
